name: como_llegar
description: Mapa de buses en Maldonado.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  http: ^1.1.0
  path:
  sqflite: ^2.3.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  flutter_map: ^6.0.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.6

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon64.png"
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon128.png" # only available for Android 8.0 devices and above

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon128.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true
